version: '3'
services:
   backend:
      restart: always
      ports:
         - "8199:3000"
      environment:
         - NODE_ENV=production
         - MONGODB_URI=mongodb://mongo/conduit
   mongo:
      ports:
         - "27017:27017"
   frontend:
      restart: always
      ports:
         - "8081:4100"
      environment:
         - NODE_ENV=production
         - API_ROOT=https://conduit.productionready.io/api
networks:
   application:
      ipam:
         driver: default
         config:
            - subnet: 172.27.7.0/25
   database:
      ipam:
         driver: default
         config:
            - subnet: 172.27.7.128/26
